language: node_js
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls
>>>>>>> d4d981aa6b1ff674c781542b3ec8af2f481fe97f
